services:
  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: node-backend
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/public/uploads:/app/src/public/uploads
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: node-frontend
    ports:
      - "3100:3100"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge