services:
  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: node-backend
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge